using System;
using Refit;
using Splat;
using WeatherAppGoogleAuth.Helpers;
using WeatherAppGoogleAuth.Services.Abstract;
using WeatherAppGoogleAuth.ViewModels;

namespace WeatherAppGoogleAuth.Services
{
    /// <summary>
    /// Container to implement IoC and initialize services, etc.
    /// </summary>
    public class ContainerInitializer : IContainerInitializer
    {
        //Initialize the Container
        public void Initialize()
        {
            RegisterServices();
        }

        public void RegisterServices()
        {
            //Register the autogenerated HttpClient by Refit as a constant
            Locator.CurrentMutable.RegisterConstant(RestService.For<IRestService>(ApiDataAccess.OpenWeatherMapAPI));

            //Register the LoginViewModel
            Locator.CurrentMutable.Register(()=> new LoginViewModel());

            //Register the WeatherPageViewModel
            Locator.CurrentMutable.Register(() => new WeatherPageViewModel());
        }
    }
}
